# The configuration in this docker-compose file
# is not a part of the cloud provisining in this repository.
# The intent is to use it for local development/testing

version: '3'
services:
  app:
    build: .
    container_name: smash_counter
    ports:
      - 8080:80

    volumes:
      - ./container_volume:/mnt

    environment:
      RDS_HOSTNAME: "${RDS_HOSTNAME}"
      RDS_USERNAME: "${RDS_USERNAME}"
      RDS_PASSWORD: "${RDS_PASSWORD}"
      RDS_PORT: "${RDS_PORT}"
      DB_NAME: "${DB_NAME}"

    env_file:
      - ./.env